### ISSUE TITLE
book: document how to run `hickory-dns` (binary) as a recursive resolver

### ISSUE THREAD

**Issue by japaric** [hickory-dns/hickory-dns.github.io#2]
as far as I could tell the steps are:

1. `cargo install hickory-dns --features recursor`

2. create `/etc/named.toml` with the contents

``` toml
[[zones]]
zone = "."
zone_type = "Hint"
stores = { type = "recursor", roots = "/etc/root.hints" }
```

In production, `/etc/root.hints` should be fetched from https://www.iana.org/domains/root/files 

3. Run `hickory-dns`

4. Check with `dig @localhost A www.example.com.`

It should be noted that, currently, DNSSEC validation is disabled and cannot be enabled.

---

if that sounds about right, I can submit a PR with the above information.

maybe some information about `_cache_size` should be included. 

same for `zone_type`. should it ever be set to some other variant for this use case?
